[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Explicitly specify Go version
  GO_VERSION = "1.19"
  GO_IMPORT_PATH = "github.com/otouristas/sifnosforanimals"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
