[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  # Explicitly specify Node.js version
  NODE_VERSION = "16.19.1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
