[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Specify Node.js version that meets Next.js requirements and is supported by Netlify
  NODE_VERSION = "18.18.0"  # Supported by Netlify and meets Next.js requirements
  # Explicitly disable Go usage
  GO_IMPORT_PATH = ""
  GO_VERSION = ""

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

[[plugins]]
  package = "@netlify/plugin-nextjs"
