[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Specify Node.js version (using a valid LTS version)
  NODE_VERSION = "18.17.1"  # This is a valid Node.js LTS version
  # Explicitly disable Go usage
  GO_IMPORT_PATH = ""
  GO_VERSION = ""

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

[[plugins]]
  package = "@netlify/plugin-nextjs"
